/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import components.RoundedBorders;

/**
 *
 * @author Pablo
 */
public class SMTPView extends javax.swing.JFrame {

    /**
     * Creates new form SMTP_View
     */
    public SMTPView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        smtpViewContainer = new javax.swing.JPanel();
        tittleSmtp = new javax.swing.JLabel();
        btnGmail = new components.RoundedBorders();
        LabelImgGmail = new javax.swing.JLabel();
        labelTxtGmail = new javax.swing.JLabel();
        btnOutlook = new components.RoundedBorders();
        labelImgOutlook = new javax.swing.JLabel();
        labelTxtOutlook = new javax.swing.JLabel();
        btnPersonalized = new components.RoundedBorders();
        labelImgPersonalized = new javax.swing.JLabel();
        labelTxtPersonalized = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(60, 62, 117));
        setFocusCycleRoot(false);
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);

        smtpViewContainer.setBackground(new java.awt.Color(60, 62, 117));
        smtpViewContainer.setMaximumSize(new java.awt.Dimension(1000, 700));
        smtpViewContainer.setMinimumSize(new java.awt.Dimension(1000, 700));
        smtpViewContainer.setPreferredSize(new java.awt.Dimension(1000, 700));
        smtpViewContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tittleSmtp.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        tittleSmtp.setForeground(new java.awt.Color(255, 255, 255));
        tittleSmtp.setText("Selecciona el proveedor SMTP");
        smtpViewContainer.add(tittleSmtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 59, 700, -1));

        btnGmail.setBackground(new java.awt.Color(50, 52, 103));
        btnGmail.setForeground(new java.awt.Color(50, 52, 103));
        btnGmail.setPreferredSize(new java.awt.Dimension(200, 200));

        LabelImgGmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Gmail_icon.png"))); // NOI18N
        btnGmail.add(LabelImgGmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, 104));
        LabelImgGmail.getAccessibleContext().setAccessibleName("Gmail_icon");

        labelTxtGmail.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelTxtGmail.setForeground(new java.awt.Color(255, 255, 255));
        labelTxtGmail.setText("Gmail");
        btnGmail.add(labelTxtGmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        smtpViewContainer.add(btnGmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 242, 250, 250));

        btnOutlook.setBackground(new java.awt.Color(50, 52, 103));
        btnOutlook.setForeground(new java.awt.Color(50, 52, 103));

        labelImgOutlook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Office_Icon.png"))); // NOI18N
        btnOutlook.add(labelImgOutlook, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        labelTxtOutlook.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelTxtOutlook.setForeground(new java.awt.Color(255, 255, 255));
        labelTxtOutlook.setText("Outlook");
        btnOutlook.add(labelTxtOutlook, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        smtpViewContainer.add(btnOutlook, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 242, 250, 250));

        btnPersonalized.setBackground(new java.awt.Color(50, 52, 103));
        btnPersonalized.setForeground(new java.awt.Color(50, 52, 103));

        labelImgPersonalized.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Personalized_icon.png"))); // NOI18N
        btnPersonalized.add(labelImgPersonalized, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        labelTxtPersonalized.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        labelTxtPersonalized.setForeground(new java.awt.Color(255, 255, 255));
        labelTxtPersonalized.setText("Personalizado");
        btnPersonalized.add(labelTxtPersonalized, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        smtpViewContainer.add(btnPersonalized, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 242, 250, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(smtpViewContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(smtpViewContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SMTPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SMTPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SMTPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SMTPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SMTPView().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImgGmail;
    private components.RoundedBorders btnGmail;
    private components.RoundedBorders btnOutlook;
    private components.RoundedBorders btnPersonalized;
    private javax.swing.JLabel labelImgOutlook;
    private javax.swing.JLabel labelImgPersonalized;
    private javax.swing.JLabel labelTxtGmail;
    private javax.swing.JLabel labelTxtOutlook;
    private javax.swing.JLabel labelTxtPersonalized;
    private javax.swing.JPanel smtpViewContainer;
    private javax.swing.JLabel tittleSmtp;
    // End of variables declaration//GEN-END:variables

    public RoundedBorders getBtnGmail() {
        return btnGmail;
    }

    public void setBtnGmail(RoundedBorders Gmail_button) {
        this.btnGmail = Gmail_button;
    }

    public RoundedBorders getBtnOutlook() {
        return btnOutlook;
    }

    public void setBtnOutlook(RoundedBorders Outlook_button) {
        this.btnOutlook = Outlook_button;
    }

    public RoundedBorders getBtnPersonalized() {
        return btnPersonalized;
    }

    public void setBtnPersonalized(RoundedBorders Personalized_button) {
        this.btnPersonalized = Personalized_button;
    }
}
