/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

/**
 *
 * @author PC GOOSE
 */
public class BackgroundImageComponent extends javax.swing.JPanel {

    /**
     * Creates new form BackgroundImageComponent
     */
    public BackgroundImageComponent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBgImg = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(552, 700));
        setMinimumSize(new java.awt.Dimension(552, 700));
        setPreferredSize(new java.awt.Dimension(552, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBgImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/paisaje-digital-en-atardecer_3840x2160_xtrafondos.com.png"))); // NOI18N
        lblBgImg.setFocusable(false);
        lblBgImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblBgImg.setMaximumSize(new java.awt.Dimension(560, 700));
        lblBgImg.setMinimumSize(new java.awt.Dimension(560, 700));
        lblBgImg.setPreferredSize(new java.awt.Dimension(560, 700));
        add(lblBgImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 570, 700));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBgImg;
    // End of variables declaration//GEN-END:variables
}
