/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

/**
 *
 * @author Pablo
 */
public class FolderItem extends javax.swing.JPanel {

    /**
     * Creates new form FolderItem
     */
    public FolderItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Folder_item = new components.RoundedBorders();
        folder_Messages_Counter = new javax.swing.JLabel();
        folder_Name = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Folder_item.setBackground(new java.awt.Color(50, 52, 103));

        folder_Messages_Counter.setForeground(new java.awt.Color(90, 91, 128));
        folder_Messages_Counter.setText("15");
        Folder_item.add(folder_Messages_Counter, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 15, -1, -1));

        folder_Name.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        folder_Name.setForeground(new java.awt.Color(255, 255, 255));
        folder_Name.setText("INBOX");
        Folder_item.add(folder_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, -1, -1));

        add(Folder_item, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 50));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.RoundedBorders Folder_item;
    private javax.swing.JLabel folder_Messages_Counter;
    private javax.swing.JLabel folder_Name;
    // End of variables declaration//GEN-END:variables
}
