/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 *
 * @author PC GOOSE
 */
public class MailContentComponent extends javax.swing.JPanel {
    
    /**
     * Creates new form mailContentView
     */
    public MailContentComponent() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new components.RoundedBorders();
        mailSenderContent = new javax.swing.JPanel();
        circleName = new components.CircleForm();
        labelShortName = new javax.swing.JLabel();
        infoSender = new javax.swing.JPanel();
        txtSenderName = new javax.swing.JLabel();
        txtSubjectMail = new javax.swing.JLabel();
        txtSenderMail = new javax.swing.JLabel();
        mailTime = new javax.swing.JPanel();
        labelDate = new javax.swing.JLabel();
        labelTime = new javax.swing.JLabel();
        mailTextContent = new javax.swing.JPanel();
        bottonContentPanel = new components.RoundedBorders();
        btnResponse = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(558, 700));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentPanel.setMaximumSize(new java.awt.Dimension(500, 700));
        contentPanel.setPreferredSize(new java.awt.Dimension(510, 584));

        mailSenderContent.setBackground(new java.awt.Color(102, 0, 51));
        mailSenderContent.setOpaque(false);
        mailSenderContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        circleName.setBackground(new java.awt.Color(204, 204, 255));

        labelShortName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelShortName.setForeground(new java.awt.Color(90, 91, 128));
        labelShortName.setText("N");

        javax.swing.GroupLayout circleNameLayout = new javax.swing.GroupLayout(circleName);
        circleName.setLayout(circleNameLayout);
        circleNameLayout.setHorizontalGroup(
            circleNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, circleNameLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(labelShortName)
                .addGap(22, 22, 22))
        );
        circleNameLayout.setVerticalGroup(
            circleNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(circleNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelShortName, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        mailSenderContent.add(circleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 60));

        infoSender.setOpaque(false);
        infoSender.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSenderName.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        txtSenderName.setText("sender name");
        infoSender.add(txtSenderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, -1));

        txtSubjectMail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSubjectMail.setText("subject");
        infoSender.add(txtSubjectMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 340, -1));

        txtSenderMail.setText("sender mail");
        infoSender.add(txtSenderMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 340, -1));

        mailSenderContent.add(infoSender, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 340, -1));

        mailTime.setOpaque(false);
        mailTime.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDate.setText("MM/DD");
        mailTime.add(labelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        labelTime.setText("HH:MM");
        mailTime.add(labelTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        mailSenderContent.add(mailTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 50, 40));

        contentPanel.add(mailSenderContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 110));

        mailTextContent.setOpaque(false);
        mailTextContent.setLayout(new java.awt.BorderLayout());
        contentPanel.add(mailTextContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 490, 430));

        add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 23, -1, -1));

        bottonContentPanel.setPreferredSize(new java.awt.Dimension(552, 70));

        btnResponse.setBackground(new java.awt.Color(194, 195, 237));
        btnResponse.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnResponse.setForeground(new java.awt.Color(114, 115, 168));
        btnResponse.setText("Responder");
        btnResponse.setAlignmentY(0.0F);
        btnResponse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnResponse.setPreferredSize(new java.awt.Dimension(123, 38));
        btnResponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponseActionPerformed(evt);
            }
        });
        bottonContentPanel.add(btnResponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        add(bottonContentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResponseActionPerformed

    public JButton getBtnResponse() {
        return btnResponse;
    }

    

  

    public JLabel getTxtSenderMail() {
        
        return txtSenderMail;
    }

    public JLabel getTxtSenderName() {
        return txtSenderName;
    }

    public JLabel getTxtSubjectMail() {
        return txtSubjectMail;
    }

  

    public JPanel getMailTextContent() {
        return mailTextContent;
    }

    public JLabel getLabelDate() {
        return labelDate;
    }

    public JLabel getLabelShortName() {
        return labelShortName;
    }

    public JLabel getLabelTime() {
        return labelTime;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.RoundedBorders bottonContentPanel;
    private javax.swing.JButton btnResponse;
    private components.CircleForm circleName;
    private components.RoundedBorders contentPanel;
    private javax.swing.JPanel infoSender;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelShortName;
    private javax.swing.JLabel labelTime;
    private javax.swing.JPanel mailSenderContent;
    private javax.swing.JPanel mailTextContent;
    private javax.swing.JPanel mailTime;
    private javax.swing.JLabel txtSenderMail;
    private javax.swing.JLabel txtSenderName;
    private javax.swing.JLabel txtSubjectMail;
    // End of variables declaration//GEN-END:variables
}
