
package components;

import javax.swing.JLabel;
import javax.swing.JPanel;


public class MailItem extends javax.swing.JPanel {

    public MailItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedBorders1 = new components.RoundedBorders();
        circleName = new components.CircleForm();
        labelShortName = new javax.swing.JLabel();
        labelTime = new javax.swing.JLabel();
        viewStatus = new components.CircleForm();
        labelDate = new javax.swing.JLabel();
        emailDataPanel = new javax.swing.JPanel();
        labelSenderName = new javax.swing.JLabel();
        labelShortMessage = new javax.swing.JLabel();
        labelSubject = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(360, 100));
        setMinimumSize(new java.awt.Dimension(360, 100));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(360, 100));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedBorders1.setBackground(new java.awt.Color(50, 52, 103));
        roundedBorders1.setMaximumSize(new java.awt.Dimension(360, 100));
        roundedBorders1.setMinimumSize(new java.awt.Dimension(360, 100));
        roundedBorders1.setPreferredSize(new java.awt.Dimension(360, 100));

        circleName.setBackground(new java.awt.Color(255, 255, 255));

        labelShortName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelShortName.setForeground(new java.awt.Color(90, 91, 128));
        labelShortName.setText("N");

        javax.swing.GroupLayout circleNameLayout = new javax.swing.GroupLayout(circleName);
        circleName.setLayout(circleNameLayout);
        circleNameLayout.setHorizontalGroup(
            circleNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(circleNameLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(labelShortName)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        circleNameLayout.setVerticalGroup(
            circleNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(circleNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelShortName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        roundedBorders1.add(circleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        labelTime.setText("1:52 pm");
        roundedBorders1.add(labelTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        viewStatus.setBackground(new java.awt.Color(231, 99, 39));
        viewStatus.setForeground(new java.awt.Color(231, 99, 39));

        javax.swing.GroupLayout viewStatusLayout = new javax.swing.GroupLayout(viewStatus);
        viewStatus.setLayout(viewStatusLayout);
        viewStatusLayout.setHorizontalGroup(
            viewStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        viewStatusLayout.setVerticalGroup(
            viewStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        roundedBorders1.add(viewStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 10, 10));

        labelDate.setText("11/13/22");
        roundedBorders1.add(labelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        emailDataPanel.setMaximumSize(new java.awt.Dimension(230, 80));
        emailDataPanel.setMinimumSize(new java.awt.Dimension(230, 80));
        emailDataPanel.setOpaque(false);
        emailDataPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSenderName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelSenderName.setText("Name");
        emailDataPanel.add(labelSenderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        labelShortMessage.setText("message");
        emailDataPanel.add(labelShortMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        labelSubject.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelSubject.setText("Subject");
        emailDataPanel.add(labelSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        roundedBorders1.add(emailDataPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 230, 80));

        add(roundedBorders1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 100));
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getEmailDataPanel() {
        return emailDataPanel;
    }

    public void setEmailDataPanel(JPanel emailDataPanel) {
        this.emailDataPanel = emailDataPanel;
    }

    public JLabel getLabelDate() {
        return labelDate;
    }

    public void setLabelDate(JLabel labelDate) {
        this.labelDate = labelDate;
    }

    public JLabel getLabelSenderName() {
        return labelSenderName;
    }

    public void setLabelSenderName(JLabel labelSenderName) {
        this.labelSenderName = labelSenderName;
    }

    public JLabel getLabelShortMessage() {
        return labelShortMessage;
    }

    public void setLabelShortMessage(JLabel labelShortMessage) {
        this.labelShortMessage = labelShortMessage;
    }

    public JLabel getLabelShortName() {
        return labelShortName;
    }

    public void setLabelShortName(JLabel labelShortName) {
        this.labelShortName = labelShortName;
    }

    public JLabel getLabelSubject() {
        return labelSubject;
    }

    public void setLabelSubject(JLabel labelSubject) {
        this.labelSubject = labelSubject;
    }

    public JLabel getLabelTime() {
        return labelTime;
    }

    public void setLabelTime(JLabel labelTime) {
        this.labelTime = labelTime;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.CircleForm circleName;
    private javax.swing.JPanel emailDataPanel;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelSenderName;
    private javax.swing.JLabel labelShortMessage;
    private javax.swing.JLabel labelShortName;
    private javax.swing.JLabel labelSubject;
    private javax.swing.JLabel labelTime;
    private components.RoundedBorders roundedBorders1;
    private components.CircleForm viewStatus;
    // End of variables declaration//GEN-END:variables
}
