
package components;

import javax.swing.JLabel;


public class MailItem extends javax.swing.JPanel {

    public MailItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedBorders1 = new components.RoundedBorders();
        circleName = new components.CircleForm();
        jLabel2 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        viewStatus = new components.CircleForm();
        date = new javax.swing.JLabel();
        emailDataPanel = new javax.swing.JPanel();
        emailName = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        subject = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(360, 100));
        setMinimumSize(new java.awt.Dimension(360, 100));
        setPreferredSize(new java.awt.Dimension(360, 100));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedBorders1.setBackground(new java.awt.Color(50, 52, 103));
        roundedBorders1.setMaximumSize(new java.awt.Dimension(360, 100));
        roundedBorders1.setMinimumSize(new java.awt.Dimension(360, 100));
        roundedBorders1.setPreferredSize(new java.awt.Dimension(360, 100));

        circleName.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(90, 91, 128));
        jLabel2.setText("N");

        javax.swing.GroupLayout circleNameLayout = new javax.swing.GroupLayout(circleName);
        circleName.setLayout(circleNameLayout);
        circleNameLayout.setHorizontalGroup(
            circleNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(circleNameLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        circleNameLayout.setVerticalGroup(
            circleNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(circleNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        roundedBorders1.add(circleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        time.setText("1:52 pm");
        roundedBorders1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        viewStatus.setBackground(new java.awt.Color(231, 99, 39));
        viewStatus.setForeground(new java.awt.Color(231, 99, 39));

        javax.swing.GroupLayout viewStatusLayout = new javax.swing.GroupLayout(viewStatus);
        viewStatus.setLayout(viewStatusLayout);
        viewStatusLayout.setHorizontalGroup(
            viewStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        viewStatusLayout.setVerticalGroup(
            viewStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        roundedBorders1.add(viewStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 10, 10));

        date.setText("11/13/22");
        roundedBorders1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        emailDataPanel.setMaximumSize(new java.awt.Dimension(230, 80));
        emailDataPanel.setMinimumSize(new java.awt.Dimension(230, 80));
        emailDataPanel.setOpaque(false);
        emailDataPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        emailName.setText("Name");
        emailDataPanel.add(emailName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        message.setText("message");
        emailDataPanel.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        subject.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        subject.setText("Subject");
        emailDataPanel.add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        roundedBorders1.add(emailDataPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 230, 80));

        add(roundedBorders1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 100));
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getDate() {
        return date;
    }

    public void setDate(JLabel date) {
        this.date = date;
    }

    public JLabel getMessage() {
        return message;
    }

    public void setMessage(JLabel message) {
        this.message = message;
    }

    public JLabel getEmailName() {
        return emailName;
    }

    public void setName(JLabel name) {
        this.emailName = name;
    }

    public JLabel getSubject() {
        return emailName;
    }

    public void setSubject(JLabel subject) {
        this.emailName = subject;
    }

    public JLabel getTime() {
        return time;
    }

    public void setTime(JLabel time) {
        this.time = time;
    }

    public CircleForm getViewStatus() {
        return viewStatus;
    }

    public void setViewStatus(CircleForm viewStatus) {
        this.viewStatus = viewStatus;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.CircleForm circleName;
    private javax.swing.JLabel date;
    private javax.swing.JPanel emailDataPanel;
    private javax.swing.JLabel emailName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel message;
    private components.RoundedBorders roundedBorders1;
    private javax.swing.JLabel subject;
    private javax.swing.JLabel time;
    private components.CircleForm viewStatus;
    // End of variables declaration//GEN-END:variables
}
