/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

/**
 *
 * @author PC GOOSE
 */
public class MailContentComponent extends javax.swing.JPanel {

    /**
     * Creates new form mailContentView
     */
    public MailContentComponent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContent = new components.RoundedBorders();
        panelMailSenderContent = new javax.swing.JPanel();
        panelProfPicSender = new javax.swing.JPanel();
        txtProfilePic = new javax.swing.JLabel();
        panelInfoSender = new javax.swing.JPanel();
        txtSenderName = new javax.swing.JLabel();
        txtSubjectMail = new javax.swing.JLabel();
        txtSenderMail = new javax.swing.JLabel();
        panelMailTime = new javax.swing.JPanel();
        txtDate = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        panelMailTextContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaMailText = new javax.swing.JTextArea();
        PanelbottonContent = new components.RoundedBorders();
        btnResponse = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(558, 700));
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContent.setMaximumSize(new java.awt.Dimension(500, 700));
        panelContent.setPreferredSize(new java.awt.Dimension(510, 584));

        panelMailSenderContent.setBackground(new java.awt.Color(102, 0, 51));
        panelMailSenderContent.setOpaque(false);
        panelMailSenderContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelProfPicSender.setBackground(new java.awt.Color(153, 0, 51));
        panelProfPicSender.setOpaque(false);
        panelProfPicSender.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtProfilePic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtProfilePic.setText("PP");
        panelProfPicSender.add(txtProfilePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        panelMailSenderContent.add(panelProfPicSender, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        panelInfoSender.setOpaque(false);
        panelInfoSender.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSenderName.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        txtSenderName.setText("sender name");
        panelInfoSender.add(txtSenderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtSubjectMail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSubjectMail.setText("subject");
        panelInfoSender.add(txtSubjectMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        txtSenderMail.setText("sender mail");
        panelInfoSender.add(txtSenderMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        panelMailSenderContent.add(panelInfoSender, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 160, -1));

        panelMailTime.setOpaque(false);
        panelMailTime.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDate.setText("MM/DD");
        panelMailTime.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtTime.setText("HH:MM");
        panelMailTime.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        panelMailSenderContent.add(panelMailTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 50, 40));

        panelContent.add(panelMailSenderContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 110));

        panelMailTextContent.setOpaque(false);
        panelMailTextContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);

        txtAreaMailText.setEditable(false);
        txtAreaMailText.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaMailText.setColumns(20);
        txtAreaMailText.setForeground(new java.awt.Color(50, 52, 103));
        txtAreaMailText.setRows(5);
        txtAreaMailText.setText("\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non \nmolestie est. Etiam suscipit in mi et interdum. Suspendisse porta libero \nsem, in porta ex fermentum nec. Aenean nec sagittis libero. Curabitur a \nmalesuada mi. Vestibulum in consectetur felis. Aliquam erat volutpat. \nEtiam condimentum nulla ex. Maecenas hendrerit dui est, in vestibulum \nligula aliquam sit amet. Ut turpis odio, dignissim et efficitur vitae, \ndictum vitae urna. Praesent accumsan massa at lorem ultrices, a aliquet \nsem hendrerit.\n\nMaecenas sodales sapien convallis sapien posuere, at efficitur ligula \nimperdiet. Donec sed mollis lacus, at tincidunt sapien. Praesent fringilla \nin est et pretium. Nam vitae lorem enim. Sed facilisis ultricies eros. \nMaecenas sagittis lectus a nisi vehicula semper. Curabitur quis efficitur \norci, id dictum felis. Nullam sed libero a tellus sagittis rutrum ut pretium \nmetus. Mauris velit risus, scelerisque quis leo ac, hendrerit sagittis nunc. \nAenean convallis arcu metus, vel maximus augue pellentesque in. Fusce \nut velit egestas sem volutpat ullamcorper. Cras laoreet neque non erat \nhendrerit fermentum. ");
        txtAreaMailText.setBorder(null);
        txtAreaMailText.setDisabledTextColor(new java.awt.Color(50, 52, 103));
        txtAreaMailText.setEnabled(false);
        txtAreaMailText.setMargin(new java.awt.Insets(2, 20, 2, 6));
        txtAreaMailText.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(txtAreaMailText);

        panelMailTextContent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 430));

        panelContent.add(panelMailTextContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 490, 430));

        add(panelContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 23, -1, -1));

        PanelbottonContent.setPreferredSize(new java.awt.Dimension(552, 70));

        btnResponse.setBackground(new java.awt.Color(194, 195, 237));
        btnResponse.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnResponse.setForeground(new java.awt.Color(114, 115, 168));
        btnResponse.setText("Responder");
        btnResponse.setAlignmentY(0.0F);
        btnResponse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnResponse.setPreferredSize(new java.awt.Dimension(123, 38));
        btnResponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponseActionPerformed(evt);
            }
        });
        PanelbottonContent.add(btnResponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        add(PanelbottonContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResponseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private components.RoundedBorders PanelbottonContent;
    private javax.swing.JButton btnResponse;
    private javax.swing.JScrollPane jScrollPane1;
    private components.RoundedBorders panelContent;
    private javax.swing.JPanel panelInfoSender;
    private javax.swing.JPanel panelMailSenderContent;
    private javax.swing.JPanel panelMailTextContent;
    private javax.swing.JPanel panelMailTime;
    private javax.swing.JPanel panelProfPicSender;
    private javax.swing.JTextArea txtAreaMailText;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtProfilePic;
    private javax.swing.JLabel txtSenderMail;
    private javax.swing.JLabel txtSenderName;
    private javax.swing.JLabel txtSubjectMail;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables
}
