/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

/**
 *
 * @author PC GOOSE
 */
public class NewMailComponent extends javax.swing.JPanel {

    /**
     * Creates new form NewMailComponent
     */
    public NewMailComponent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContent = new components.RoundedBorders();
        panelMailSenderContent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSubject = new javax.swing.JLabel();
        txtContactName = new javax.swing.JLabel();
        panelMailTextContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        aTxtMailText = new javax.swing.JTextArea();
        panelButtonContent = new components.RoundedBorders();
        btnCancel = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContent.setMaximumSize(new java.awt.Dimension(500, 700));
        panelContent.setPreferredSize(new java.awt.Dimension(510, 584));

        panelMailSenderContent.setBackground(new java.awt.Color(102, 0, 51));
        panelMailSenderContent.setOpaque(false);
        panelMailSenderContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(50, 52, 103));
        jLabel1.setText("Correo nuevo");
        panelMailSenderContent.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 490, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 490, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 490, -1));

        jLabel2.setForeground(new java.awt.Color(90, 91, 128));
        jLabel2.setText("De: ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtUserName.setForeground(new java.awt.Color(90, 91, 128));
        txtUserName.setText("User name");
        jPanel2.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 470, -1));

        jLabel3.setForeground(new java.awt.Color(90, 91, 128));
        jLabel3.setText("Para:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jLabel4.setForeground(new java.awt.Color(90, 91, 128));
        jLabel4.setText("Asunto:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        txtSubject.setForeground(new java.awt.Color(90, 91, 128));
        txtSubject.setText("Subject");
        jPanel2.add(txtSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 430, -1));

        txtContactName.setForeground(new java.awt.Color(90, 91, 128));
        txtContactName.setText("Contact name");
        jPanel2.add(txtContactName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 460, -1));

        panelMailSenderContent.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 490, 100));

        panelContent.add(panelMailSenderContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 160));

        panelMailTextContent.setOpaque(false);
        panelMailTextContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);

        aTxtMailText.setColumns(20);
        aTxtMailText.setForeground(new java.awt.Color(50, 52, 103));
        aTxtMailText.setLineWrap(true);
        aTxtMailText.setRows(5);
        aTxtMailText.setText("Mensaje:");
        aTxtMailText.setBorder(null);
        aTxtMailText.setDisabledTextColor(new java.awt.Color(50, 52, 103));
        aTxtMailText.setMargin(new java.awt.Insets(2, 20, 2, 6));
        aTxtMailText.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(aTxtMailText);

        panelMailTextContent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 490, 410));

        panelContent.add(panelMailTextContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 490, 400));

        add(panelContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, -1, -1));

        panelButtonContent.setPreferredSize(new java.awt.Dimension(552, 70));

        btnCancel.setBackground(new java.awt.Color(50, 52, 103));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Enviar");
        btnCancel.setAlignmentY(0.0F);
        btnCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancel.setPreferredSize(new java.awt.Dimension(89, 38));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        panelButtonContent.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        btnSend.setBackground(new java.awt.Color(194, 195, 237));
        btnSend.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnSend.setForeground(new java.awt.Color(114, 115, 168));
        btnSend.setText("Cancelar");
        btnSend.setAlignmentY(0.0F);
        btnSend.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSend.setPreferredSize(new java.awt.Dimension(89, 38));
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        panelButtonContent.add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        add(panelButtonContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea aTxtMailText;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private components.RoundedBorders panelButtonContent;
    private components.RoundedBorders panelContent;
    private javax.swing.JPanel panelMailSenderContent;
    private javax.swing.JPanel panelMailTextContent;
    private javax.swing.JLabel txtContactName;
    private javax.swing.JLabel txtSubject;
    private javax.swing.JLabel txtUserName;
    // End of variables declaration//GEN-END:variables
}
